on:
  push:
    branches:
      - main
  #schedule:
  #  - cron: 40 3 * * 0
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/duplicacy
    steps:
      - uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - run: DOCKER_BUILDKIT=1 docker build -f Containerfile -t ${{ env.IMAGE }} .
      - name: docker tag ...
        run: |
          set -x
          VERSION=$(
            docker run --rm -i ${{ env.IMAGE }} help \
              | awk '/^VERSION/ { l = NR + 1 }; NR == l && $1 ~ /^[0-9.]+$/ { print $1 }'
          )
          [ -n "$VERSION" ] || exit
          docker tag ${{ env.IMAGE }} ${{ env.IMAGE }}:"$VERSION"
      - run: docker push -a ${{ env.IMAGE }}
