on:
  push:
    branches:
      - main
  #schedule:
  #  - cron: 40 3 * * 0
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/duplicacy
    steps:
      - uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - run: DOCKER_BUILDKIT=1 docker build -f Containerfile -t ${{ env.IMAGE }} .
      - run: |
          for v in "2.7.2"; do
            docker tag ${{ env.IMAGE }} ${{ env.IMAGE }}:"$v"
          done
      - run: docker push -a ${{ env.IMAGE }}
